umc_config:
    type: data
	
	title: Block Margin
	subtitle: everything we test
	login_time: 1h
	monster_spawn_limit: 30
	
	# -- overworld
	
	world_max_y: 319
	world_min_y: -63
	

	#<script[umc_config].data_key[monster_spawn_limit]>
	
	stats: ANIMALS_BRED|ARMOR_CLEANED|AVIATE_ONE_CM|BANNER_CLEANED|BEACON_INTERACTION|BELL_RING|BOAT_ONE_CM|BREAK_ITEM|BREWINGSTAND_INTERACTION|CAKE_SLICES_EATEN|CAULDRON_FILLED|CAULDRON_USED|CHEST_OPENED|CLEAN_SHULKER_BOX|CLIMB_ONE_CM|CRAFT_ITEM|CRAFTING_TABLE_INTERACTION|CROUCH_ONE_CM|DAMAGE_ABSORBED|DAMAGE_BLOCKED_BY_SHIELD|DAMAGE_DEALT|DAMAGE_DEALT_ABSORBED|DAMAGE_DEALT_RESISTED|DAMAGE_RESISTED|DAMAGE_TAKEN|DEATHS|DISPENSER_INSPECTED|DROP|DROP_COUNT|DROPPER_INSPECTED|ENDERCHEST_OPENED|ENTITY_KILLED_BY|FALL_ONE_CM|FISH_CAUGHT|FLOWER_POTTED|FLY_ONE_CM|FURNACE_INTERACTION|HOPPER_INSPECTED|HORSE_ONE_CM|INTERACT_WITH_ANVIL|INTERACT_WITH_BLAST_FURNACE|INTERACT_WITH_CAMPFIRE|INTERACT_WITH_CARTOGRAPHY_TABLE|INTERACT_WITH_GRINDSTONE|INTERACT_WITH_LECTERN|INTERACT_WITH_LOOM|INTERACT_WITH_SMITHING_TABLE|INTERACT_WITH_SMOKER|INTERACT_WITH_STONECUTTER|ITEM_ENCHANTED|JUMP|KILL_ENTITY|LEAVE_GAME|MINE_BLOCK|MINECART_ONE_CM|MOB_KILLS|NOTEBLOCK_PLAYED|NOTEBLOCK_TUNED|OPEN_BARREL|PICKUP|PIG_ONE_CM|PLAY_ONE_MINUTE|PLAYER_KILLS|RAID_TRIGGER|RAID_WIN|RECORD_PLAYED|SHULKER_BOX_OPENED|SLEEP_IN_BED|SNEAK_TIME|SPRINT_ONE_CM|STRIDER_ONE_CM|SWIM_ONE_CM|TALKED_TO_VILLAGER|TARGET_HIT|TIME_SINCE_DEATH|TIME_SINCE_REST|TOTAL_WORLD_TIME|TRADED_WITH_VILLAGER|TRAPPED_CHEST_TRIGGERED|USE_ITEM|WALK_ON_WATER_ONE_CM|WALK_ONE_CM|WALK_UNDER_WATER_ONE_CM	
	
	entity: Animals|Creature|Monster|Villager
		
#	AbstractArrow, AbstractHorse, AbstractSkeleton, 
#	AbstractVillager, Ageable, Allay, Ambient, 
#	Animals, 
#	AreaEffectCloud, ArmorStand, Arrow, Axolotl, Bat, Bee, Blaze, Boat, Boss, 
#	Breedable, Cat, CaveSpider, ChestBoat, ChestedHorse, Chicken, Cod, CommandMinecart, ComplexEntityPart, ComplexLivingEntity, Cow, 
#	Creature, Creeper, Damageable, Dolphin, Donkey, DragonFireball, Drowned, Egg, ElderGuardian, EnderCrystal, EnderDragon, EnderDragonPart, Enderman, Endermite, EnderPearl, EnderSignal, 
#	Evoker, EvokerFangs, ExperienceOrb, Explosive, ExplosiveMinecart, FallingBlock, Fireball, Firework, Fish, FishHook, Flying, Fox, Frog, Ghast, Giant, GlowItemFrame, GlowSquid, Goat, Golem, 
#	Guardian, Hanging, Hoglin, HopperMinecart, Horse, 
#	HumanEntity, Husk, Illager, Illusioner, IronGolem, Item, ItemFrame, LargeFireball, LeashHitch, LightningStrike, LingeringPotion, LivingEntity, Llama, LlamaSpit, MagmaCube, Marker, Minecart, 
#	Mob, 
#	Monster, Mule, MushroomCow, 
#	NPC, Ocelot, Painting, Panda, Parrot, Phantom, Pig, Piglin, PiglinAbstract, PiglinBrute, PigZombie, Pillager, Player, PolarBear, PoweredMinecart, Projectile, PufferFish, Rabbit, Raider, Ravager, RideableMinecart, Salmon, Sheep, Shulker, ShulkerBullet, Silverfish, SizedFireball, Skeleton, SkeletonHorse, Slime, SmallFireball, Snowball, Snowman, SpawnerMinecart, SpectralArrow, Spellcaster, Spider, SplashPotion, Squid, Steerable, StorageMinecart, Stray, Strider, Tadpole, 
#	Tameable, ThrowableProjectile, ThrownExpBottle, ThrownPotion, TippedArrow, TNTPrimed, TraderLlama, Trident, TropicalFish, Turtle, Vehicle, Vex, 
#	Villager, Vindicator, WanderingTrader, Warden, WaterMob, Witch, Wither, WitherSkeleton, WitherSkull, Wolf, Zoglin, Zombie, ZombieHorse, ZombieVillager	
	
	potflower: 
		_flower: POTTED_FLOWERING_AZALEA_BUSH|POTTED_BLUE_ORCHID|POTTED_CORNFLOWER|POTTED_DANDELION|POTTED_LILY_OF_THE_VALLEY|POTTED_ORANGE_TULIP|POTTED_OXEYE_DAISY|POTTED_PINK_TULIP|POTTED_WHITE_TULIP|POTTED_POPPY|POTTED_RED_TULIP|POTTED_ALLIUM|POTTED_AZURE_BLUET
		_bonzai: POTTED_ACACIA_SAPLING|POTTED_BIRCH_SAPLING|POTTED_DARK_OAK_SAPLING|POTTED_OAK_SAPLING|POTTED_SPRUCE_SAPLING|POTTED_JUNGLE_SAPLING
		_woods: POTTED_BAMBOO|POTTED_CACTUS|POTTED_DEAD_BUSH|POTTED_FERN
		_mushroom: POTTED_AZALEA_BUSH|POTTED_WITHER_ROSE|POTTED_RED_MUSHROOM|POTTED_BROWN_MUSHROOM
		_crimson: POTTED_CRIMSON_FUNGUS|POTTED_CRIMSON_ROOTS|POTTED_WARPED_FUNGUS|POTTED_WARPED_ROOTS

	plants:
		small: FLOWERING_AZALEA_BUS/H|BLUE_ORCHID|CORNFLOWER|DANDELION|LILY_OF_THE_VALLEY|ORANGE_TULIP|OXEYE_DAISY|PINK_TULIP|WHITE_TULIP|POPPY|RED_TULIP|ALLIUM|AZURE_BLUET|AZALEA_BUSH
		tall: LILAC|ROSE_BUSH|PEONY|SUNFLOWER
		
	flowers: FLOWERING_AZALEA_BUSH|BLUE_ORCHID|CORNFLOWER|DANDELION|LILY_OF_THE_VALLEY|ORANGE_TULIP|OXEYE_DAISY|PINK_TULIP|WHITE_TULIP|POPPY|RED_TULIP|ALLIUM|AZURE_BLUET|ACACIA_SAPLING|BIRCH_SAPLING|DARK_OAK_SAPLING|OAK_SAPLING|SPRUCE_SAPLING|JUNGLE_SAPLING|BAMBOO|CACTUS|DEAD_BUSH|FERN|AZALEA_BUSH|WITHER_ROSE|RED_MUSHROOM|BROWN_MUSHROOM|CRIMSON_FUNGUS|CRIMSON_ROOTS|WARPED_FUNGUS|WARPED_ROOTS
	
	villager:
		color: PLAINS|TAIGA|DESERT|JUNGLE|SAVANNA|SNOW|SWAMP
		prof: FARMER|FISHERMAN|SHEPHERD|BUTCHER|LEATHERWORKER|TOOLSMITH|MASON|FLETCHER|WEAPONSMITH|CARTOGRAPHER|CLERIC|LIBRARIAN|NITWIT
		
	disguise: 
		color: ZOMBIE|ZOMBIE_VILLAGER|PILLAGER|PIGLIN|STRAY|WITCH|DROWNED|HUSK|EVOKER|VINDICATOR|WANDERING_TRADER|PIGLIN_BRUTE

